version: '3.3'
services:
  mongo-yad2-price-monitor:
    image: mongo
    container_name: "mongo-yad2-price-monitor"
    restart: always
    entrypoint: ["tail", "-f", "/dev/null"]
    working_dir: $PWD
    ports:
      - "27018:27017"  # Map container port 27017 to host port 27018
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example