version: '3.3'
services:
  convexum-pybuilder:
    image: cvxm.jfrog.io/cvxm-dockerhub/devops/convexum-pybuilder:focal
    container_name: "pybuilder"
    restart: always
    entrypoint: ["tail", "-f", "/dev/null"]
    working_dir: $PWD
    volumes:
      - type: bind
        source: $PWD
        target: $PWD
        read_only: false
      - type: bind
        source: $HOME/.ssh
        target: /root/.ssh
        read_only: true
      - type: bind
        source: $HOME/.pip
        target: /root/.pip
        read_only: true